src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Le nom est obligatoire.')]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Le code raccourci est obligatoire.')]
    private ?string $code_raccourci = null;

    #[ORM\OneToMany(mappedBy: 'categorie', targetEntity: Licencie::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Collection $licencie;

    public function __construct()
    {
        $this->licencie = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCodeRaccourci(): ?string
    {
        return $this->code_raccourci;
    }

    public function setCodeRaccourci(string $code_raccourci): static
    {
        $this->code_raccourci = $code_raccourci;

        return $this;
    }

    public function getLicencie(): ?Collection
    {
        return $this->licencie;
    }

    public function addLicencie(Licencie $licencie): static
    {
        if (!$this->licencie->contains($licencie)) {
            $this->licencie->add($licencie);
            $licencie->setCategorie($this);
        }

        return $this;
    }

    public function removeLicencie(Licencie $licencie): static
    {
        if ($this->licencie->contains($licencie)) {
            $this->licencie->removeElement($licencie);
            if ($licencie->getCategorie() === $this) {
                $licencie->setCategorie(null);
            }
        }

        return $this;
    }
}

src/Entity/Licencie.php
<?php

namespace App\Entity;

use App\Repository\LicencieRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: LicencieRepository::class)]
class Licencie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::SMALLINT,unique: true)]
    #[Assert\Positive(message: 'Le numéro de licence doit être un nombre positif.')]
    private ?int $numeroLicence = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Le nom est obligatoire.')]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: 'Le prénom est obligatoire.')]
    private ?string $prenom = null;

    #[ORM\ManyToOne(inversedBy: 'licencie')]
    #[ORM\JoinColumn(nullable: true,onDelete: 'SET NULL')]
    private ?Categorie $categorie = null;

    #[ORM\ManyToOne(inversedBy: 'licencie')]
    #[ORM\JoinColumn(nullable: true,onDelete: 'SET NULL')]
    private ?Contact $contact = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroLicence(): ?int
    {
        return $this->numeroLicence;
    }

    public function setNumeroLicence(int $numeroLicence): static
    {
        $this->numeroLicence = $numeroLicence;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getContact(): ?Contact
    {
        return $this->contact;
    }

    public function setContact(?Contact $contact): static
    {
        $this->contact = $contact;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/LicencieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\Contact;
use App\Entity\Licencie;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class LicencieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('numeroLicence', NumberType::class, [
                'label' => 'Numéro de licence',
                'label_attr' => [
                    'class' => 'form-label mt-2'
                ],
                'attr' => [
                    'class' => 'form-control',
                    'min' => 0,
                    'max' => 999999999999999,
                    'placeholder' => 'Entrez votre numéro de licence'
                ],
                'constraints' => [
                    new Assert\Positive([
                        'message' => 'Le numéro de licence doit être un nombre positif.'
                    ])
                ]
            ])
            ->add('nom', TextType::class, [
                'label' => 'Nom',
                'label_attr' => [
                    'class' => 'form-label mt-2'
                ],
                'attr' => [
                    'class' => 'form-control',
                    'minlength' => 3,
                    'maxlength' => 50,
                    'placeholder' => 'Entrez votre nom'
                ],
                'constraints' => [
                    new Assert\Length([
                        'min' => 3,
                        'max' => 50,
                        'minMessage' => 'Le nom doit contenir au moins {{ limit }} caractères',
                        'maxMessage' => 'Le nom doit contenir au maximum {{ limit }} caractères'
                    ]),
                    new Assert\NotBlank([
                        'message' => 'Le nom est obligatoire'
                    ])
                ]
            ])
            ->add('prenom', TextType::class, [
                'label' => 'Prénom',
                'label_attr' => [
                    'class' => 'form-label mt-2'
                ],
                'attr' => [
                    'class' => 'form-control',
                    'minlength' => 3,
                    'maxlength' => 50,
                    'placeholder' => 'Entrez votre prénom'
                ],
                'constraints' => [
                    new Assert\Length([
                        'min' => 3,
                        'max' => 50,
                        'minMessage' => 'Le prénom doit contenir au moins {{ limit }} caractères',
                        'maxMessage' => 'Le prénom doit contenir au maximum {{ limit }} caractères'
                    ]),
                    new Assert\NotBlank([
                        'message' => 'Le prénom est obligatoire'
                    ])
                ]
            ])
            ->add('categorie', EntityType::class, [
                'class' => Categorie::class,
'choice_label' => 'nom',
                'label' => 'Catégorie',
                'label_attr' => [
                    'class' => 'form-label mt-2'
                ],
                'attr' => [
                    'class' => 'form-control'
                ],
                'constraints' => [
                    new Assert\NotBlank([
                        'message' => 'La catégorie est obligatoire'
                    ])
                ]
            ])
            ->add('contact', EntityType::class, [
                'class' => Contact::class,
'choice_label' => 'email',
                'label' => 'Contact',
                'label_attr' => [
                    'class' => 'form-label mt-2'
                ],
                'attr' => [
                    'class' => 'form-control'
                ],
                'constraints' => [
                    new Assert\NotBlank([
                        'message' => 'Le contact est obligatoire'
                    ])
                ]

            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Enregistrer',
                'attr' => [
                    'class' => 'btn btn-primary mt-3'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Licencie::class,
        ]);
    }
}

src/Controller/LicencieController.php
<?php

namespace App\Controller;

use App\Entity\Licencie;
use App\Form\CategorieType;
use App\Form\LicencieType;
use App\Repository\LicencieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class LicencieController extends AbstractController
{
    #[Route('/licencie', name: 'licencie.index', methods: ['GET'])]
    public function index(LicencieRepository $repository,PaginatorInterface $paginator, Request $request): Response
    {
        $licencies = $paginator->paginate(
            $repository->findAll(),
            $request->query->getInt('page', 1),
            5
        );
        return $this->render('pages/licencie/index.html.twig', [
            'licencies' => $licencies
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('licencie/new', name: 'licencie.new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
        $licencie = new Licencie();
        $form = $this->createForm(LicencieType::class, $licencie);
        $form->handleRequest($request);
        if ($form->isSubmitted() and $form->isValid()) {
            $categorie = $form->getData();
            $manager->persist($categorie);
            $manager->flush();
            $this->addFlash('success', 'Le licencie a bien été ajoutée.');
            return $this->redirectToRoute('licencie.index');
        }
        return $this->render('pages/licencie/new.html.twig',
            [
                'form' => $form->createView()
            ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/licencie/edition/{id}', name: 'licencie.edit', methods: ['GET', 'POST'])]
    public function edit(Licencie $licencie, Request $request, EntityManagerInterface $manager): Response
    {
        $form = $this->createForm(LicencieType::class, $licencie);
        $form->handleRequest($request);
        if ($form->isSubmitted() and $form->isValid()) {
            $licencie = $form->getData();
            $manager->persist($licencie);
            $manager->flush();
            $this->addFlash('success', 'Le licencie a bien été modifiée.');
            return $this->redirectToRoute('licencie.index');
        }
        return $this->render('pages/licencie/edit.html.twig',
            [
                'form' => $form->createView()
            ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/licencie/suppression/{id}', name: 'licencie.delete', methods: ['GET'])]
    public function delete(Licencie $licencie,EntityManagerInterface $manager): Response
    {
        $manager->remove($licencie);
        $manager->flush();
        $this->addFlash('success', 'Le licencié a bien été supprimée.');
        return $this->redirectToRoute('licencie.index');
    }
}

templates/pages/licencie/edit.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">

        <h1 class="mt-4">Modifier un Licencié</h1>
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_label(form.nom) }}
            {{ form_widget(form.nom) }}
            {{ form_errors(form.nom) }}
        </div>
        <div class="form-group">
            {{ form_label(form.prenom) }}
            {{ form_widget(form.prenom) }}
            {{ form_errors(form.prenom) }}
        </div>
        <div class="form-group">
            {{ form_label(form.numeroLicence) }}
            {{ form_widget(form.numeroLicence) }}
            {{ form_errors(form.numeroLicence) }}
        </div>
        <div class="form-group">
            {{ form_label(form.categorie) }}
            {{ form_widget(form.categorie) }}
            {{ form_errors(form.categorie) }}
        </div>
        <div class="form-group">
            {{ form_label(form.contact) }}
            {{ form_widget(form.contact) }}
            {{ form_errors(form.contact) }}
        <div class="form-group">
            {{ form_row(form.submit) }}
        </div>
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/pages/licencie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello LicencieController!{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1 class="text-center">Liste des licenciés</h1>
        <div class="d-flex justify-content-end">
            <a href="{{ path('licencie.new') }}" class="btn btn-primary mb-4">Ajouter un licencié</a>
        </div>
        {% for message in  app.flashes('success') %}
            <div class=" alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        {% if licencies is not empty %}
            <table class="table table-hover mt-4">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">Numéro de licence</th>
                    <th scope="col">Catégrorie</th>
                    <th scope="col">Email du contact</th>
                    <th scope="col">Edition</th>
                    <th scope="col">Suppression</th>
                </tr>
                </thead>
                <tbody>
                {% for licencie in licencies %}
                    <tr class="table-dark">
                        {% if licencie.categorie is not null %}
                        <th scope="row">{{ licencie.id }}</th>
                        <td>{{ licencie.nom }}</td>
                        <td>{{ licencie.prenom }}</td>
                        <td>{{ licencie.numeroLicence }}</td>
                        <td>{{ licencie.categorie.codeRaccourci }}</td>
                        <td>{{ licencie.contact.email }}</td>
                        <td><a href="{{ path('licencie.edit', {'id': licencie.id}) }}" class="btn btn-primary">Editer</a></td>
                        <td><a href="{{ path('licencie.delete',{'id': licencie.id}) }}" class ="btn btn primary">Supprimer</a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="navigation d-flex justify-content-center mt-4">
                {{ knp_pagination_render(licencies) }}
            </div>
        {% else %}
            <div class="alert alert-warning" role="alert">
                Aucun licencié n'a été trouvé.
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/pages/licencie/new.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">

    <h1 class="mt-4">Modifier un Licencié</h1>
    {{ form_start(form) }}
    <div class="form-group">
        {{ form_label(form.nom) }}
        {{ form_widget(form.nom) }}
        {{ form_errors(form.nom) }}
    </div>
    <div class="form-group">
        {{ form_label(form.prenom) }}
        {{ form_widget(form.prenom) }}
        {{ form_errors(form.prenom) }}
    </div>
    <div class="form-group">
        {{ form_label(form.numeroLicence) }}
        {{ form_widget(form.numeroLicence) }}
        {{ form_errors(form.numeroLicence) }}
    </div>
    <div class="form-group">
        {{ form_label(form.categorie) }}
        {{ form_widget(form.categorie) }}
        {{ form_errors(form.categorie) }}
    </div>
    <div class="form-group">
        {{ form_label(form.contact) }}
        {{ form_widget(form.contact) }}
        {{ form_errors(form.contact) }}
    </div>
        <div class="form-group">
            {{ form_row(form.submit) }}
        </div>
        {{ form_end(form) }}
    </div>

{% endblock %}